//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LangContentT
    {
        public int ID { get; set; }
        public int LangContID { get; set; }
        public int TransID { get; set; }
        public string Text { get; set; }
    
        public virtual LangContent LangContent { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
