//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyCategoriesT
    {
        public int ID { get; set; }
        public int PropCatID { get; set; }
        public int TransID { get; set; }
        public string CategoryName { get; set; }
        public string ShortText { get; set; }
        public string Description { get; set; }
    
        public virtual PropertyCategories PropertyCategories { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
