//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValues
    {
        public int ID { get; set; }
        public int PropID { get; set; }
        public string Text { get; set; }
        public string Value { get; set; }
        public string Code { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
