//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupRights
    {
        public int ID { get; set; }
        public int UserGroupTableID { get; set; }
        public int UserGroupProcessID { get; set; }
        public bool Allow { get; set; }
    
        public virtual UserGroupProcess UserGroupProcess { get; set; }
        public virtual UserGroupTables UserGroupTables { get; set; }
    }
}
