//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class AramaKayit
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Sozcuk { get; set; }
        public bool SozcukTumu { get; set; }
        public string Sehir { get; set; }
        public int Tarih { get; set; }
        public string CalismaTipi { get; set; }
        public string Sektor { get; set; }
        public string Departman { get; set; }
        public string Pozisyon { get; set; }
        public string Egitim { get; set; }
        public string Tecrube { get; set; }
        public string Diger { get; set; }
        public int Cinsiyet { get; set; }
        public int KullaniciID { get; set; }
        public bool Aktif { get; set; }
        public string Guid { get; set; }
    }
}
