//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Derece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Derece()
        {
            this.OzgecmisBilgisayar = new HashSet<OzgecmisBilgisayar>();
            this.OzgecmisDil = new HashSet<OzgecmisDil>();
            this.OzgecmisDil1 = new HashSet<OzgecmisDil>();
            this.OzgecmisDil2 = new HashSet<OzgecmisDil>();
        }
    
        public int ID { get; set; }
        public string Baslik { get; set; }
        public int Kod { get; set; }
        public bool Aktif { get; set; }
        public string Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisBilgisayar> OzgecmisBilgisayar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDil> OzgecmisDil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDil> OzgecmisDil1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDil> OzgecmisDil2 { get; set; }
    }
}
