//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaIlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaIlan()
        {
            this.FirmaIlanSart = new HashSet<FirmaIlanSart>();
            this.FirmaIlanSorular = new HashSet<FirmaIlanSorular>();
        }
    
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public string IlanNo { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string BaslangicTarih { get; set; }
        public string BitisTarih { get; set; }
        public bool SoruAktifArac { get; set; }
        public bool SoruHaftaSonu { get; set; }
        public bool Aktif { get; set; }
        public bool Silindi { get; set; }
        public string Guid { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaIlanSart> FirmaIlanSart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaIlanSorular> FirmaIlanSorular { get; set; }
    }
}
