//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaIlanSorular
    {
        public int ID { get; set; }
        public int IlanID { get; set; }
        public bool TekCevapliSoru { get; set; }
        public string Soru { get; set; }
        public bool TekSecenekliCevap { get; set; }
        public string Secenekler { get; set; }
        public string Guid { get; set; }
    
        public virtual FirmaIlan FirmaIlan { get; set; }
    }
}
