//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaIlanSart
    {
        public int ID { get; set; }
        public int IlanID { get; set; }
        public int CalismaSekli { get; set; }
        public int Cinsiyet { get; set; }
        public int Maas { get; set; }
        public string Sehir { get; set; }
        public bool SehirSor { get; set; }
        public string Egitim { get; set; }
        public string Deneyim { get; set; }
        public string Sektor { get; set; }
        public string Departman { get; set; }
        public string Pozisyon { get; set; }
    
        public virtual FirmaIlan FirmaIlan { get; set; }
    }
}
