//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firma()
        {
            this.FirmaIlan = new HashSet<FirmaIlan>();
        }
    
        public int ID { get; set; }
        public string SirketAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KullaniciAdi { get; set; }
        public long TCKimlikNo { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public int Sektor { get; set; }
        public int Sehir { get; set; }
        public string Telefon { get; set; }
        public string CepTelefon { get; set; }
        public string Faks { get; set; }
        public string Website { get; set; }
        public string Hakkinda { get; set; }
        public string Logo { get; set; }
        public System.DateTime SonGiris { get; set; }
        public bool Aktif { get; set; }
        public bool HaberUyelik { get; set; }
        public string Guid { get; set; }
        public string Url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaIlan> FirmaIlan { get; set; }
    }
}
