//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikdbEntities : DbContext
    {
        public ikdbEntities()
            : base("name=ikdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AramaKayit> AramaKayit { get; set; }
        public virtual DbSet<Askerlik> Askerlik { get; set; }
        public virtual DbSet<BilgisayarTip> BilgisayarTip { get; set; }
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<CalismaTipi> CalismaTipi { get; set; }
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Deneyim> Deneyim { get; set; }
        public virtual DbSet<Derece> Derece { get; set; }
        public virtual DbSet<DigerSecenek> DigerSecenek { get; set; }
        public virtual DbSet<EgitimBurs> EgitimBurs { get; set; }
        public virtual DbSet<EgitimSeviye> EgitimSeviye { get; set; }
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<FirmaIlan> FirmaIlan { get; set; }
        public virtual DbSet<FirmaIlanSart> FirmaIlanSart { get; set; }
        public virtual DbSet<FirmaIlanSorular> FirmaIlanSorular { get; set; }
        public virtual DbSet<Guncellik> Guncellik { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Maas> Maas { get; set; }
        public virtual DbSet<MedeniHal> MedeniHal { get; set; }
        public virtual DbSet<Onyazi> Onyazi { get; set; }
        public virtual DbSet<OzgecmisBilgisayar> OzgecmisBilgisayar { get; set; }
        public virtual DbSet<OzgecmisCalisma> OzgecmisCalisma { get; set; }
        public virtual DbSet<OzgecmisDeneyim> OzgecmisDeneyim { get; set; }
        public virtual DbSet<OzgecmisDil> OzgecmisDil { get; set; }
        public virtual DbSet<OzgecmisDosya> OzgecmisDosya { get; set; }
        public virtual DbSet<OzgecmisEgitim> OzgecmisEgitim { get; set; }
        public virtual DbSet<OzgecmisGenel> OzgecmisGenel { get; set; }
        public virtual DbSet<OzgecmisReferans> OzgecmisReferans { get; set; }
        public virtual DbSet<OzgecmisSertifika> OzgecmisSertifika { get; set; }
        public virtual DbSet<OzgecmisSinav> OzgecmisSinav { get; set; }
        public virtual DbSet<OzgecmisTercih> OzgecmisTercih { get; set; }
        public virtual DbSet<Pozisyon> Pozisyon { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<Sektor> Sektor { get; set; }
        public virtual DbSet<Tecrube> Tecrube { get; set; }
        public virtual DbSet<TercihBolum> TercihBolum { get; set; }
        public virtual DbSet<TercihPozisyon> TercihPozisyon { get; set; }
        public virtual DbSet<TercihSektor> TercihSektor { get; set; }
    }
}
