//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.OzgecmisBilgisayar = new HashSet<OzgecmisBilgisayar>();
            this.OzgecmisCalisma = new HashSet<OzgecmisCalisma>();
            this.OzgecmisDeneyim = new HashSet<OzgecmisDeneyim>();
            this.OzgecmisDil = new HashSet<OzgecmisDil>();
            this.OzgecmisDosya = new HashSet<OzgecmisDosya>();
            this.OzgecmisEgitim = new HashSet<OzgecmisEgitim>();
            this.OzgecmisGenel = new HashSet<OzgecmisGenel>();
            this.OzgecmisReferans = new HashSet<OzgecmisReferans>();
            this.OzgecmisSertifika = new HashSet<OzgecmisSertifika>();
            this.OzgecmisSinav = new HashSet<OzgecmisSinav>();
            this.OzgecmisTercih = new HashSet<OzgecmisTercih>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
        public int Sehir { get; set; }
        public string Hakkinda { get; set; }
        public string Resim { get; set; }
        public int Cinsiyet { get; set; }
        public bool OzgecmisAktif { get; set; }
        public System.DateTime SonGiris { get; set; }
        public bool Aktif { get; set; }
        public bool HaberUyelik { get; set; }
        public string Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisBilgisayar> OzgecmisBilgisayar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisCalisma> OzgecmisCalisma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDeneyim> OzgecmisDeneyim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDil> OzgecmisDil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisDosya> OzgecmisDosya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisEgitim> OzgecmisEgitim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisGenel> OzgecmisGenel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisReferans> OzgecmisReferans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisSertifika> OzgecmisSertifika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisSinav> OzgecmisSinav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OzgecmisTercih> OzgecmisTercih { get; set; }
    }
}
