//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisBilgisayar
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int BilgisayarTipID { get; set; }
        public string Baslik { get; set; }
        public int DereceID { get; set; }
        public string Guid { get; set; }
    
        public virtual BilgisayarTip BilgisayarTip { get; set; }
        public virtual Derece Derece { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
