//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisGenel
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int SehirID { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string DogumTarih { get; set; }
        public int CinsiyetID { get; set; }
        public int MedeniHalID { get; set; }
        public int AskerlikID { get; set; }
        public string AskerlikTarih { get; set; }
        public bool Ehliyet { get; set; }
        public string EhliyetSinif { get; set; }
        public bool Sigara { get; set; }
        public int Egitim { get; set; }
    
        public virtual Askerlik Askerlik { get; set; }
        public virtual Cinsiyet Cinsiyet { get; set; }
        public virtual EgitimSeviye EgitimSeviye { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual MedeniHal MedeniHal { get; set; }
        public virtual Sehir Sehir { get; set; }
    }
}
