//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisReferans
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public string AdSoyad { get; set; }
        public string Sirket { get; set; }
        public string Gorev { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Guid { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
