//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisCalisma
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public string MeslekUnvan { get; set; }
        public bool CalismaDurumu { get; set; }
        public int DeneyimID { get; set; }
        public string KisiselBilgi { get; set; }
    
        public virtual Deneyim Deneyim { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
