//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisDeneyim
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int Tip { get; set; }
        public string SirketIsmi { get; set; }
        public int SehirID { get; set; }
        public int SektorID { get; set; }
        public int BolumID { get; set; }
        public int PozisyonID { get; set; }
        public string GirisTarih { get; set; }
        public string CikisTarih { get; set; }
        public bool Devam { get; set; }
        public string Aciklama { get; set; }
        public string Guid { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Pozisyon Pozisyon { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sektor Sektor { get; set; }
    }
}
