//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisDil
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public string Dil { get; set; }
        public int OkumaID { get; set; }
        public int YazmaID { get; set; }
        public int KonusmaID { get; set; }
        public string Guid { get; set; }
    
        public virtual Derece Derece { get; set; }
        public virtual Derece Derece1 { get; set; }
        public virtual Derece Derece2 { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
