//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisEgitim
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int SeviyeID { get; set; }
        public string Okul { get; set; }
        public string Fakulte { get; set; }
        public string Bolum { get; set; }
        public int SehirID { get; set; }
        public string BaslangicTarih { get; set; }
        public string BitisTarih { get; set; }
        public bool Devam { get; set; }
        public int BursID { get; set; }
        public string Ortalama { get; set; }
        public string Guid { get; set; }
    
        public virtual EgitimBurs EgitimBurs { get; set; }
        public virtual EgitimSeviye EgitimSeviye { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Sehir Sehir { get; set; }
    }
}
