//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzgecmisTercih
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OzgecmisTercih()
        {
            this.TercihBolum = new HashSet<TercihBolum>();
            this.TercihPozisyon = new HashSet<TercihPozisyon>();
            this.TercihSektor = new HashSet<TercihSektor>();
        }
    
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int MaasID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Maas Maas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TercihBolum> TercihBolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TercihPozisyon> TercihPozisyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TercihSektor> TercihSektor { get; set; }
    }
}
