//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKProjeAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TercihPozisyon
    {
        public int ID { get; set; }
        public int TercihID { get; set; }
        public int PozisyonID { get; set; }
    
        public virtual OzgecmisTercih OzgecmisTercih { get; set; }
        public virtual Pozisyon Pozisyon { get; set; }
    }
}
