//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AngularJSExercises
    {
        public int ID { get; set; }
        public int CatID { get; set; }
        public string Picture { get; set; }
    
        public virtual AngularJSCategories AngularJSCategories { get; set; }
    }
}
