//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyHaftaBolge
    {
        public int ID { get; set; }
        public int HaftaID { get; set; }
        public int BolgeID { get; set; }
    
        public virtual BodyBolgeler BodyBolgeler { get; set; }
        public virtual BodyHafta BodyHafta { get; set; }
    }
}
