//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyBolgeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BodyBolgeler()
        {
            this.BodyEgzersiz = new HashSet<BodyEgzersiz>();
            this.BodyHaftaBolge = new HashSet<BodyHaftaBolge>();
        }
    
        public int ID { get; set; }
        public string BolgeAdi { get; set; }
        public string BolgeAdiTr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyEgzersiz> BodyEgzersiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyHaftaBolge> BodyHaftaBolge { get; set; }
    }
}
