//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuitarNota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuitarNota()
        {
            this.GuitarPlanAralik = new HashSet<GuitarPlanAralik>();
            this.GuitarPlanAkor = new HashSet<GuitarPlanAkor>();
            this.GuitarPlanMod = new HashSet<GuitarPlanMod>();
        }
    
        public int ID { get; set; }
        public string Isim { get; set; }
        public string Isim2 { get; set; }
        public Nullable<int> Isim3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuitarPlanAralik> GuitarPlanAralik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuitarPlanAkor> GuitarPlanAkor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuitarPlanMod> GuitarPlanMod { get; set; }
    }
}
