//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuitarPlanMod
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int NotaID { get; set; }
        public int ModID { get; set; }
    
        public virtual GuitarMod GuitarMod { get; set; }
        public virtual GuitarNota GuitarNota { get; set; }
        public virtual GuitarPlanlar GuitarPlanlar { get; set; }
    }
}
