//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int ID { get; set; }
        public int LinkTypeID { get; set; }
        public int LinkID { get; set; }
    
        public virtual LinkTypes LinkTypes { get; set; }
    }
}
