//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryLang
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string ShortText { get; set; }
        public string LongText { get; set; }
        public Nullable<int> Language { get; set; }
    }
}
