//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ceyhanpolatdbEntities : DbContext
    {
        public ceyhanpolatdbEntities()
            : base("name=ceyhanpolatdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryLang> CategoryLang { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentLang> ContentLang { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<PicturesNoLang> PicturesNoLang { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<RankPoint> RankPoint { get; set; }
    }
}
