//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyhanPolat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ID { get; set; }
        public string GalleryName { get; set; }
        public Nullable<int> RoutePageID { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<int> Queue { get; set; }
        public string RouteUrl { get; set; }
    }
}
