//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmlakSiteEntities : DbContext
    {
        public EmlakSiteEntities()
            : base("name=EmlakSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryLang> CategoryLang { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentLang> ContentLang { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<FilesLang> FilesLang { get; set; }
        public virtual DbSet<FilesNoLang> FilesNoLang { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<GalleryLang> GalleryLang { get; set; }
        public virtual DbSet<Lang> Lang { get; set; }
        public virtual DbSet<PanelMenu> PanelMenu { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<PicturesLang> PicturesLang { get; set; }
        public virtual DbSet<PicturesNoLang> PicturesNoLang { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<RankPoint> RankPoint { get; set; }
        public virtual DbSet<RealEstateAds> RealEstateAds { get; set; }
        public virtual DbSet<RealEstateAdsLang> RealEstateAdsLang { get; set; }
        public virtual DbSet<SiteDesign> SiteDesign { get; set; }
        public virtual DbSet<URLink> URLink { get; set; }
        public virtual DbSet<URLinkLang> URLinkLang { get; set; }
        public virtual DbSet<URLinkNoLang> URLinkNoLang { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
