//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;

    public partial class PanelMenu
    {
        public PanelMenu()
        {
            this.SubMenuItems = new List<PanelMenu>();
        }

        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Title { get; set; }
        public bool Active { get; set; }
        public Nullable<int> OrderNo { get; set; }

        public List<PanelMenu> SubMenuItems { get; set; }

        public dynamic AggColumn { get; set; }
    }
}
