//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class PicturesLang
    {
        public int ID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string PictureName { get; set; }
        public string ShortText { get; set; }
        public string Description { get; set; }
        public Nullable<int> Language { get; set; }

        [JsonIgnore]
        public virtual Lang Lang { get; set; }
        [JsonIgnore]
        public virtual Pictures Pictures { get; set; }

        public dynamic AggColumn { get; set; }
    }
}
