//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class RankPoint
    {
        public int ID { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> RankPoint1 { get; set; }
        public string IPAddress { get; set; }
        public string Sender { get; set; }
        public string SendDate { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool Active { get; set; }

        public dynamic AggColumn { get; set; }

        [JsonIgnore]
        public virtual Rank Rank { get; set; }
    }
}
