//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Rank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rank()
        {
            this.RankPoint = new HashSet<RankPoint>();
        }

        public int ID { get; set; }
        public string RankName { get; set; }
        public string Code { get; set; }
        public Nullable<int> MaxRankPoint { get; set; }
        public Nullable<bool> Active { get; set; }

        public dynamic AggColumn { get; set; }
        public dynamic Sample { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<RankPoint> RankPoint { get; set; }
    }
}
