//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class RealEstateAdsLang
    {
        public int ID { get; set; }
        public Nullable<int> EmlakID { get; set; }
        public string Baslik { get; set; }
        public string Code { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Language { get; set; }

        public dynamic AggColumn { get; set; }

        [JsonIgnore]
        public virtual Lang Lang { get; set; }
        [JsonIgnore]
        public virtual RealEstateAds RealEstateAds { get; set; }
    }
}
