//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;

    public partial class SiteDesign
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Order { get; set; }
        public bool LeftSide { get; set; }
        public bool Show { get; set; }

        public dynamic AggColumn { get; set; }
    }
}
